services:
    downloader:
        class: Pitchart\Typo3Installer\Service\Downloader
        arguments: ['get.typo3.org']
    extractor:
        class: Pitchart\Typo3Installer\Service\TarExtractor
    permissionsFixer:
        class: Pitchart\Typo3Installer\Service\PermissionsFixer
